language: c
addons:
    apt:
        packages:
        - build-essential
        - cmake

before_script:
    - cp scripts/install-googletest.sh $TRAVIS_BUILD_DIR
    - chmod +x $TRAVIS_BUILD_DIR/install-googletest.sh
    - pushd $TRAVIS_BUILD_DIR && ./install-googletest.sh && popd

script:
  - cd src
  - cmake .
  - make
  - ./bin/square_root_tests

