language: c
addons:
    apt:
        packages:
        - build-essential
        - cmake

before_script:
    - pushd $TRAVIS_BUILD_DIR && git clone https://github.com/google/googletest && mkdir -p googletest/build && pushd googletest/build && cmake ..  && sudo make install && popd && popd

script:
  - cmake .
  - make
  - ./bin/square_root_tests

